import { useState, useEffect, useMemo } from "react";
import { useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { PageHeader } from "@/components/common/PageHeader";
import { DataTable, Column } from "@/components/common/DataTable";
import { StatusBadge } from "@/components/common/StatusBadge";
import { EmptyState } from "@/components/common/EmptyState";
import { OrderDetailModal } from "@/components/orders/OrderDetailModal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Plus, ClipboardList, Search, ArrowUpDown, ArrowUp, ArrowDown } from "lucide-react";
import type { Order, Project, OrderStatus } from "@/types/database";
import { format } from "date-fns";

interface OrderWithProject extends Order {
  project: Project;
}

type SortField = "created_at" | "expected_delivery_date" | "total_amount";
type SortDirection = "asc" | "desc";

// Active statuses for filtering - includes Delivered as per spec
const ACTIVE_STATUSES: OrderStatus[] = [
  "for_approval",
  "approved",
  "submitted",
  "preparing",
  "in_transit",
  "delivered",
  "on_hold",
];

export default function Orders() {
  const [searchParams, setSearchParams] = useSearchParams();
  const { user } = useAuth();
  const { toast } = useToast();
  const [orders, setOrders] = useState<OrderWithProject[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  // Initialize status filter from URL params
  const urlStatus = searchParams.get("status");
  const [statusFilter, setStatusFilter] = useState<string>(urlStatus || "all");

  const [sortField, setSortField] = useState<SortField>("created_at");
  const [sortDirection, setSortDirection] = useState<SortDirection>("desc");
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    project_id: "",
    supplier_name: "",
    supplier_contact: "",
    expected_delivery_date: "",
    notes: "",
  });

  // Update URL when filter changes
  useEffect(() => {
    if (statusFilter === "all") {
      searchParams.delete("status");
    } else {
      searchParams.set("status", statusFilter);
    }
    setSearchParams(searchParams, { replace: true });
  }, [statusFilter, searchParams, setSearchParams]);

  const fetchData = async () => {
    // Fetch all orders with project info, including closed orders
    const { data: ordersData } = await supabase
      .from("orders")
      .select("*, project:projects(*)")
      .in("status", [
        "for_approval",
        "approved",
        "submitted",
        "preparing",
        "in_transit",
        "delivered",
        "rejected",
        "on_hold",
        "closed",
      ])
      .order("created_at", { ascending: false });
    console.log(ordersData);
    // Filter to only show orders from active projects
    const activeProjectOrders = (ordersData || []).filter((order: any) => order.project?.status === "active");

    setOrders(activeProjectOrders as OrderWithProject[]);

    const { data: projectsData } = await supabase.from("projects").select("*").eq("status", "active");

    setProjects((projectsData || []) as Project[]);

    setLoading(false);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleCreateOrder = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!user) return;

    const { error } = await supabase.from("orders").insert({
      project_id: formData.project_id,
      supplier_name: formData.supplier_name || null,
      supplier_contact: formData.supplier_contact || null,
      expected_delivery_date: formData.expected_delivery_date || null,
      notes: formData.notes || null,
      created_by: user.id,
      order_number: "", // Will be auto-generated by trigger
    });

    if (error) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } else {
      toast({ title: "Success", description: "Order created successfully" });
      setIsDialogOpen(false);
      setFormData({
        project_id: "",
        supplier_name: "",
        supplier_contact: "",
        expected_delivery_date: "",
        notes: "",
      });
      fetchData();
    }
  };

  const handleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc");
    } else {
      setSortField(field);
      setSortDirection("desc");
    }
  };

  const getSortIcon = (field: SortField) => {
    if (sortField !== field) {
      return <ArrowUpDown className="h-4 w-4 text-muted-foreground" />;
    }
    return sortDirection === "asc" ? (
      <ArrowUp className="h-4 w-4 text-primary" />
    ) : (
      <ArrowDown className="h-4 w-4 text-primary" />
    );
  };

  const filteredAndSortedOrders = useMemo(() => {
    let result = orders.filter((order) => {
      const matchesSearch =
        order.order_number?.toLowerCase().includes(search.toLowerCase()) ||
        order.supplier_name?.toLowerCase().includes(search.toLowerCase()) ||
        order.project?.name?.toLowerCase().includes(search.toLowerCase());

      // Handle 'active' filter specially - includes all active statuses
      let matchesStatus = false;
      if (statusFilter === "all") {
        matchesStatus = true;
      } else if (statusFilter === "active") {
        matchesStatus = ACTIVE_STATUSES.includes(order.status);
      } else {
        matchesStatus = order.status === statusFilter;
      }
      console.log(matchesSearch);
      console.log(matchesStatus);
      return matchesSearch && matchesStatus;
    });

    // Sort
    result.sort((a, b) => {
      let aVal: number | string | null = null;
      let bVal: number | string | null = null;

      switch (sortField) {
        case "created_at":
          aVal = a.created_at;
          bVal = b.created_at;
          break;
        case "expected_delivery_date":
          aVal = a.expected_delivery_date || "";
          bVal = b.expected_delivery_date || "";
          break;
        case "total_amount":
          aVal = a.total_amount ?? 0;
          bVal = b.total_amount ?? 0;
          break;
      }

      if (aVal === null || aVal === "") return sortDirection === "asc" ? 1 : -1;
      if (bVal === null || bVal === "") return sortDirection === "asc" ? -1 : 1;

      if (aVal < bVal) return sortDirection === "asc" ? -1 : 1;
      if (aVal > bVal) return sortDirection === "asc" ? 1 : -1;
      return 0;
    });

    return result;
  }, [orders, search, statusFilter, sortField, sortDirection]);

  const columns: Column<OrderWithProject>[] = [
    {
      key: "order_number",
      header: "Order #",
      render: (order) => <span className="font-medium">{order.order_number}</span>,
    },
    {
      key: "project",
      header: "Project",
      render: (order) => <span className="text-muted-foreground">{order.project?.name}</span>,
    },
    {
      key: "supplier",
      header: "Supplier",
      render: (order) => order.supplier_name || "-",
    },
    {
      key: "status",
      header: "Status",
      render: (order) => <StatusBadge status={order.status} />,
    },
    {
      key: "expected_delivery",
      header: (
        <button
          className="flex items-center gap-1 hover:text-primary transition-colors"
          onClick={() => handleSort("expected_delivery_date")}
        >
          Expected Delivery
          {getSortIcon("expected_delivery_date")}
        </button>
      ) as unknown as string,
      render: (order) =>
        order.expected_delivery_date ? format(new Date(order.expected_delivery_date), "MMM d, yyyy") : "-",
    },
    {
      key: "total",
      header: (
        <button
          className="flex items-center gap-1 hover:text-primary transition-colors"
          onClick={() => handleSort("total_amount")}
        >
          Amount
          {getSortIcon("total_amount")}
        </button>
      ) as unknown as string,
      render: (order) =>
        order.total_amount ? `₱${order.total_amount.toLocaleString("en-PH", { minimumFractionDigits: 2 })}` : "-",
      className: "text-right",
    },
    {
      key: "created",
      header: (
        <button
          className="flex items-center gap-1 hover:text-primary transition-colors"
          onClick={() => handleSort("created_at")}
        >
          Created
          {getSortIcon("created_at")}
        </button>
      ) as unknown as string,
      render: (order) => format(new Date(order.created_at), "MMM d, yyyy"),
    },
  ];

  // Updated status options with all statuses including closed
  const statusOptions: { value: string; label: string }[] = [
    { value: "all", label: "All Statuses" },
    { value: "active", label: "Active Orders" },
    { value: "for_approval", label: "Order Requested" },
    { value: "approved", label: "Approved" },
    { value: "submitted", label: "Submitted" },
    { value: "preparing", label: "Preparing for Tracking" },
    { value: "in_transit", label: "On Transit" },
    { value: "delivered", label: "Delivered" },
    { value: "closed", label: "Completed" },
    { value: "rejected", label: "Rejected" },
    { value: "on_hold", label: "On-hold" },
  ];

  if (!loading && orders.length === 0) {
    return (
      <div className="animate-fade-in">
        <PageHeader title="View Orders" description="Manage purchase orders and track deliveries" />
        <EmptyState
          icon={ClipboardList}
          title="No orders yet"
          description="Create your first purchase order to start tracking procurement."
          action={{
            label: "Create Order",
            onClick: () => setIsDialogOpen(true),
          }}
        />
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      <PageHeader title="Orders" description="Manage purchase orders and track deliveries" />

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search orders..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-[200px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {statusOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <DataTable
        columns={columns}
        data={filteredAndSortedOrders}
        loading={loading}
        emptyMessage="No orders found"
        onRowClick={(order) => setSelectedOrderId(order.id)}
      />

      <OrderDetailModal
        orderId={selectedOrderId}
        open={!!selectedOrderId}
        onOpenChange={(open) => !open && setSelectedOrderId(null)}
        onStatusChange={fetchData}
      />
    </div>
  );
}
