import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { PageHeader } from '@/components/common/PageHeader';
import { DataTable, Column } from '@/components/common/DataTable';
import { StatusBadge } from '@/components/common/StatusBadge';
import { EmptyState } from '@/components/common/EmptyState';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { Plus, ClipboardList, Search } from 'lucide-react';
import type { Order, Project, OrderStatus } from '@/types/database';
import { format } from 'date-fns';

interface OrderWithProject extends Order {
  project: Project;
}

export default function Orders() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { toast } = useToast();
  const [orders, setOrders] = useState<OrderWithProject[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    project_id: '',
    supplier_name: '',
    supplier_contact: '',
    expected_delivery_date: '',
    notes: '',
  });

  const fetchData = async () => {
    const { data: ordersData } = await supabase
      .from('orders')
      .select('*, project:projects(*)')
      .order('created_at', { ascending: false });

    setOrders((ordersData || []) as OrderWithProject[]);

    const { data: projectsData } = await supabase
      .from('projects')
      .select('*')
      .eq('status', 'active');

    setProjects((projectsData || []) as Project[]);

    setLoading(false);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleCreateOrder = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!user) return;

    const { error } = await supabase.from('orders').insert({
      project_id: formData.project_id,
      supplier_name: formData.supplier_name || null,
      supplier_contact: formData.supplier_contact || null,
      expected_delivery_date: formData.expected_delivery_date || null,
      notes: formData.notes || null,
      created_by: user.id,
      order_number: '', // Will be auto-generated by trigger
    });

    if (error) {
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    } else {
      toast({ title: 'Success', description: 'Order created successfully' });
      setIsDialogOpen(false);
      setFormData({
        project_id: '',
        supplier_name: '',
        supplier_contact: '',
        expected_delivery_date: '',
        notes: '',
      });
      fetchData();
    }
  };

  const filteredOrders = orders.filter((order) => {
    const matchesSearch =
      order.order_number?.toLowerCase().includes(search.toLowerCase()) ||
      order.supplier_name?.toLowerCase().includes(search.toLowerCase()) ||
      order.project?.name?.toLowerCase().includes(search.toLowerCase());

    const matchesStatus = statusFilter === 'all' || order.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const columns: Column<OrderWithProject>[] = [
    {
      key: 'order_number',
      header: 'Order #',
      render: (order) => (
        <span className="font-medium">{order.order_number}</span>
      ),
    },
    {
      key: 'project',
      header: 'Project',
      render: (order) => (
        <span className="text-muted-foreground">{order.project?.name}</span>
      ),
    },
    {
      key: 'supplier',
      header: 'Supplier',
      render: (order) => order.supplier_name || '-',
    },
    {
      key: 'status',
      header: 'Status',
      render: (order) => <StatusBadge status={order.status} />,
    },
    {
      key: 'expected_delivery',
      header: 'Expected Delivery',
      render: (order) =>
        order.expected_delivery_date
          ? format(new Date(order.expected_delivery_date), 'MMM d, yyyy')
          : '-',
    },
    {
      key: 'total',
      header: 'Amount',
      render: (order) =>
        order.total_amount ? `$${order.total_amount.toLocaleString()}` : '-',
      className: 'text-right',
    },
    {
      key: 'created',
      header: 'Created',
      render: (order) => format(new Date(order.created_at), 'MMM d, yyyy'),
    },
  ];

  const statusOptions: { value: string; label: string }[] = [
    { value: 'all', label: 'All Statuses' },
    { value: 'draft', label: 'Draft' },
    { value: 'for_approval', label: 'For Approval' },
    { value: 'approved', label: 'Approved' },
    { value: 'ordered', label: 'Ordered' },
    { value: 'in_transit', label: 'In Transit' },
    { value: 'delivered', label: 'Delivered' },
    { value: 'partially_received', label: 'Partially Received' },
    { value: 'fully_received', label: 'Fully Received' },
    { value: 'closed', label: 'Closed' },
    { value: 'cancelled', label: 'Cancelled' },
  ];

  if (!loading && orders.length === 0) {
    return (
      <div className="animate-fade-in">
        <PageHeader
          title="Orders"
          description="Manage purchase orders and track deliveries"
        />
        <EmptyState
          icon={ClipboardList}
          title="No orders yet"
          description="Create your first purchase order to start tracking procurement."
          action={{
            label: 'Create Order',
            onClick: () => setIsDialogOpen(true),
          }}
        />
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      <PageHeader
        title="Orders"
        description="Manage purchase orders and track deliveries"
        action={
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="mr-2 h-4 w-4" />
                New Order
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Purchase Order</DialogTitle>
              </DialogHeader>
              <form onSubmit={handleCreateOrder} className="space-y-4">
                <div className="space-y-2">
                  <Label>Project *</Label>
                  <Select
                    value={formData.project_id}
                    onValueChange={(value) =>
                      setFormData({ ...formData, project_id: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select project" />
                    </SelectTrigger>
                    <SelectContent>
                      {projects.map((project) => (
                        <SelectItem key={project.id} value={project.id}>
                          {project.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Supplier Name</Label>
                  <Input
                    value={formData.supplier_name}
                    onChange={(e) =>
                      setFormData({ ...formData, supplier_name: e.target.value })
                    }
                    placeholder="Acme Supplies Inc."
                  />
                </div>

                <div className="space-y-2">
                  <Label>Supplier Contact</Label>
                  <Input
                    value={formData.supplier_contact}
                    onChange={(e) =>
                      setFormData({ ...formData, supplier_contact: e.target.value })
                    }
                    placeholder="Email or phone"
                  />
                </div>

                <div className="space-y-2">
                  <Label>Expected Delivery Date</Label>
                  <Input
                    type="date"
                    value={formData.expected_delivery_date}
                    onChange={(e) =>
                      setFormData({
                        ...formData,
                        expected_delivery_date: e.target.value,
                      })
                    }
                  />
                </div>

                <div className="space-y-2">
                  <Label>Notes</Label>
                  <Textarea
                    value={formData.notes}
                    onChange={(e) =>
                      setFormData({ ...formData, notes: e.target.value })
                    }
                    rows={3}
                  />
                </div>

                <div className="flex justify-end gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setIsDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button type="submit">Create Order</Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>
        }
      />

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search orders..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-[180px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {statusOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <DataTable
        columns={columns}
        data={filteredOrders}
        loading={loading}
        emptyMessage="No orders found"
        onRowClick={(order) => navigate(`/orders/${order.id}`)}
      />
    </div>
  );
}