// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klwlxkbhljwphfddlobe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsd2x4a2JobGp3cGhmZGRsb2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMTgwNjgsImV4cCI6MjA4NDg5NDA2OH0.xlUbKVLc-l8kFc8w5DOx4DuqlbVoQGGlSDKTPb4b788";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});